import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../styles/globals.css";
import Nav from "./ui/nav";


const manrop = Manrope({
  variable:"--font-manrop",
  style:['normal']
})


export const metadata: Metadata = {
  title: "E-come",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrop.variable}  antialiased`}> 
       {children}
      </body>
    </html>
  );
}
