import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../styles/globals.css";
import Nav from "./ui/nav";
import { avenir, blackMango } from "./fonts/font";




export const metadata: Metadata = {
  title: "E-come",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={` ${avenir.variable} ${blackMango.style}  antialiased`}> 
       {children}
      </body>
    </html>
  );
}
