name: Playwright + Vercel Gated Deploy

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]

jobs:
  deploy_preview:
    name: Deploy Preview to Vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v4
      
      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      # Install Node & enable pnpm caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # Build the project
      - name: Build Project
        run: pnpm build
      
      # Deploy to Vercel (Preview) using CLI directly
      - name: Vercel Preview Deploy
        id: vercel
        run: |
          # Install Vercel CLI
          npm i -g vercel@latest
          
          # Set up Vercel project configuration
          mkdir -p .vercel
          echo "{\"orgId\":\"${{ secrets.VERCEL_ORG_ID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECT_ID }}\"}" > .vercel/project.json
          
          # Deploy and capture URL
          DEPLOYMENT_URL=$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --yes)
          echo "preview-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "Preview deployed to: $DEPLOYMENT_URL"

  playwright_test:
    name: Run Playwright Tests (Preview)
    needs: deploy_preview
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PLAYWRIGHT_BASE_URL: ${{ needs.deploy_preview.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      # Cache Playwright browsers
      - name: Cache Playwright Browsers
        uses: actions/cache@v4  # Updated to v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      
      # Wait for Vercel Preview to be ready
      - name: Wait for Preview to be Ready
        run: |
          echo "Waiting for $PLAYWRIGHT_BASE_URL to respond..."
          for i in {1..60}; do  # Increased timeout
            if curl -fsS --connect-timeout 10 --max-time 30 "$PLAYWRIGHT_BASE_URL" >/dev/null 2>&1; then
              echo "Preview is live!"
              exit 0
            fi
            echo "Not ready yet... ($i/60)"
            sleep 10  # Increased sleep time
          done
          echo "Preview never became ready."
          exit 1
      
      - name: Run Playwright tests
        run: pnpm exec playwright test
      
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy_prod:
    name: Deploy to Production (after passing tests)
    needs: [playwright_test]
    if: >
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
      needs.playwright_test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Force link Vercel project
      - name: Link Vercel Project
        run: npx vercel link --token=${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }} --yes


      # Deploy to Vercel Production
      - name: Vercel Production Deploy
        run: |
          # Install Vercel CLI
          npm i -g vercel@latest
          
          # Deploy to production
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes