name: Playwright + Vercel Gated Deploy

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]

jobs:
  deploy_preview:
    name: Deploy Preview to Vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.vercel.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Install Node & enable pnpm caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Force link Vercel project
      - name: Link Vercel Project
        run: npx vercel link --token=${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }} --yes

      # Deploy to Vercel (Preview)
      - name: Vercel Preview Deploy
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: '' # no --prebuilt
          github-token: ${{ secrets.GITHUB_TOKEN }}

  playwright_test:
    name: Run Playwright Tests (Preview)
    needs: deploy_preview
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PLAYWRIGHT_BASE_URL: ${{ needs.deploy_preview.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Cache Playwright browsers
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      # Wait for Vercel Preview to be ready
      - name: Wait for Preview to be Ready
        run: |
          echo "Waiting for $PLAYWRIGHT_BASE_URL to respond..."
          for i in {1..30}; do
            if curl -fsS "$PLAYWRIGHT_BASE_URL" >/dev/null; then
              echo "Preview is live!"
              exit 0
            fi
            echo "Not ready yet... ($i/30)"
            sleep 5
          done
          echo "Preview never became ready."
          exit 1

      - name: Run Playwright tests
        run: pnpm exec playwright test --config=playwright.config.ts

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy_prod:
    name: Deploy to Production (after passing tests)
    needs: [playwright_test]
    if: >
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
      needs.playwright_test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Force link Vercel project
      - name: Link Vercel Project
        run: npx vercel link --token=${{ secrets.VERCEL_TOKEN }} --project ${{ secrets.VERCEL_PROJECT_ID }} --confirm

      # Deploy to Vercel Production
      - name: Vercel Production Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: '--prod'
          github-token: ${{ secrets.GITHUB_TOKEN }}
